# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Pairwise Distance metric for matrix
#'
#' @param x numeric matrix
#'
#' @export
#' @examples
#' mat <- matrix(1:9, ncol = 3)
#' metric_pwd(mat)
metric_pwd <- function(x) {
    .Call(`_bedslider_metric_pwd`, x)
}

