# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate MHIC metric for matrix
#'
#' @param x Numeric matrix
#' @param lower Numeric determining the lower bound.
#' @param upper Numeric determining the upper bound.
#' @export
#' @examples
#' mat <- matrix(seq(0.1, 0.9, by = 0.1), ncol = 3)
#' metric_mhic(mat)
metric_mhic <- function(x, lower = 0.2, upper = 0.8) {
    .Call(`_bedslider_metric_mhic`, x, lower, upper)
}

#' Calculate Pairwise Distance metric for matrix
#'
#' @param x numeric matrix
#'
#' @export
#' @examples
#' mat <- matrix(1:9, ncol = 3)
#' metric_pwd(mat)
metric_pwd <- function(x) {
    .Call(`_bedslider_metric_pwd`, x)
}

